export const dataProduct = [
  {
    id: 1,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product1b.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product1c.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product1b.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product1a.webp",
    ],
    color: ["#3a6380", "#773d49", "#bc2a32", "#edc582"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 20,
    priceSale: 8,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: false,
    star: 5,
    like: true,
  },
  {
    id: 2,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product11c.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product11c.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product11b.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product11a.webp",
    ],
    color: ["blue", "brown", "red", "yellow"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 25,
    priceSale: 5,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: true,
    star: 5,
    like: true,
  },
  {
    id: 3,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product5a.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product5a.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product1b-300x300.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product1c-300x300.webp",
    ],
    color: ["blue", "brown", "red", "yellow"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 65,
    priceSale: 38,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: true,
    star: 5,
    like: true,
  },
  {
    id: 4,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product2a.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product2b.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product2a.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product2c.webp",
    ],
    color: ["blue", "brown", "red", "yellow"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 15,
    priceSale: 35,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: false,
    star: 5,
    like: true,
  },
  {
    id: 5,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product7a.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product7a.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product7b.webp",
    ],
    color: ["blue", "brown", "red", "yellow"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 28,
    priceSale: 26,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: false,
    star: 5,
    like: true,
  },
  {
    id: 6,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product9c.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product9c.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product9b.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product9a.webp",
    ],
    color: ["blue", "brown", "red", "yellow"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 15,
    priceSale: 14,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: false,
    star: 5,
    like: true,
  },
  {
    id: 7,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product3a.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product3a.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product3b.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product3c.webp",
    ],
    color: ["blue", "brown", "red", "yellow"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 25,
    priceSale: 30,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: true,
    star: 5,
    like: true,
  },
  {
    id: 8,
    name: "Duvet Cover Set Be Brave",
    des: "Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a non felis eleifend justo vel bibendum sapien.",
    comment: [
      "Maecenas malesuada 5 elit lectus felis, malesuada ultricies.",
      "Curabitur et ligula. Ut molestie a, ultricies porta urna.",
      "Vestibulum commodo volutpat a, convallis ac, laoreet enim.",
      "Phasellus fermentum in, dolor. Pellentesque facilisis.",
    ],
    material: "Composition: Main material: 95% Cotton, 5% Polyester",
    imageMain:
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product6a.webp",
    image: [
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product6a.webp",
      "https://themes.muffingroup.com/be/babyshop/wp-content/uploads/2021/10/babyshop-product6b.webp",
    ],
    color: ["blue", "brown", "red", "yellow"],
    tag: ["Duvet cover", "kids", "Recyclable"],
    category: ["Bed sets"],
    sku: "BE-8727U2",
    price: 45,
    priceSale: 20,
    height: [50, 54, 58, 62, 68, 74, 82],
    age: ["0 - 2 years", "2 - 4 years "],
    sale: true,
    star: 5,
    like: true,
  },
];
